# Generated by Django 4.0.3 on 2022-03-13 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=50, null=True)),
                ('loginsCount', models.IntegerField(null=True)),
                ('lastLogin', models.DateTimeField(null=True)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
